### ISSUE TITLE
Enhancements/bug fixes to mail app

### ISSUE THREAD

**Issue by sathyanarayanant** [ishacrm/ishacrmserver#6]
1. Send to Yourself - should not suppress repeat emails
2. Make it clear how many emails have gone out
3. Plunkr ID should be changed to something generic (URL ?)
4. Sometimes when mail content is updated, the UI is not showing the latest changes

**Comment by thulasidhar** [comment]
Updated new UI for mail feature.
Please test to see if fixes all the issues mentioned.
