### ISSUE TITLE
Duplicate Id for user

### ISSUE THREAD

**Issue by Kumarakuru** [ishacrm/ishacrmserver#93]
For Dev server

For Tami akka, it created a duplicate id
![image](https://cloud.githubusercontent.com/assets/17122234/12912821/fe638f70-cf55-11e5-8ee7-ef4acfbbccbd.png)

If I login, then the page doesnt load anything

![image](https://cloud.githubusercontent.com/assets/17122234/12912808/ea0b56a2-cf55-11e5-8029-cc470b948620.png)

**Comment by thulasidhar** [comment]
We need to create a new dev env for you.
Like I has said earlier, this dev env is constantly being mirror and used
for different testing.

**Comment by Kumarakuru** [comment]
Ok anna,

But just would like to understand the reason for this duplicate id. My
concern is accidentally this (duplicate id creation) should not happen in
production.

Pranam

**Comment by thulasidhar** [comment]
The reason is that sometimes, we do selective data sync from the prod env..
at the same time I think you were creating the user in the dev env.
Thats why I said its best to have a separate env where only your updates
are there.

**Comment by thulasidhar** [comment]
Created ishacrm-sit.appspot.com
