### ISSUE TITLE
Program View - UI Issues

### ISSUE THREAD

**Issue by Kumarakuru** [ishacrm/ishacrmserver#95]
1. The list still shows as 0 (though view displays the actual data)
![image](https://cloud.githubusercontent.com/assets/17122234/13032772/75f115e8-d33a-11e5-8571-eb0294fb49ee.png)

2. The Date filter resets to initial date if we view the program and come back.
![image](https://cloud.githubusercontent.com/assets/17122234/13032774/906fa0b0-d33a-11e5-8a55-7a3287ad7aaf.png)

**Comment by thulasidhar** [comment]
The (0) is the registration count. we will change it to show both
registrations and actual participants' count.

date filter being reset is a intended feature. Please right click on the
list button and open the detailed info in a new tab/window
