### ISSUE TITLE
Error while uploading participant

### ISSUE THREAD

**Issue by Kumarakuru** [ishacrm/ishacrmserver#98]
Namaskaram Anna,
This file cleared validation but not able to upload. Gives error as null e-mail.
200 OK

- Show headers -

{
"statusCode": "ERROR_LOGIN_REQUIRED",
"userFriendlyMessage": "Email cannot be null or empty",
"kind": "participant#participantApiItem",
"etag": "\"6JisowVKwTpJX5QKcWYCm9zLXp4/PWK0STWFxIYeNzuOdl73rXy3-a4\""
}

Please help

https://docs.google.com/spreadsheets/d/1KCXA58-BIm4mm_6WOaaedzNjxzheUHiYZWdiewSIwiE/edit?ts=56c6c72b#gid=0

**Comment by thulasidhar** [comment]
This error code means that the api explorer session has expired.
Please login again and try.
